# Typed action plan generated by deterministic parser, never an arbitrary script.
# The action names are the only operations that a natural-language request may propose.
from typing import Literal
from pydantic import BaseModel, ConfigDict, Field

class Action(BaseModel):
    model_config = ConfigDict(extra="forbid")
    name: Literal["create_task", "list_calendar_events"]
    arguments: dict = Field(default_factory=dict)

class ActionPlan(BaseModel):
    model_config = ConfigDict(extra="forbid")
    actions: list[Action] = Field(min_length=1, max_length=2)
